import Head from 'next/head'
import Image from 'next/image'
import Header from './Header'
import Ratings from '../components/Ratings'
import AgentActive from '../components/AgentActive'
import ConnectSection from '../components/ConnectSection'
import AgentChat from '../components/AgentChat'
import Articles from '../components/Articles'





import AgentChoice from '../components/AgentChoice'
export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Ratings />
      <AgentChoice />
      <AgentActive />
      <ConnectSection />
      <AgentChat />
      <Articles />
    </div>
  )
}
